// <auto-generated />
using System;
using DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DBContext.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211015151955_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DBContext.Models.Connection", b =>
                {
                    b.Property<int>("ConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ConnectedToPlanetId")
                        .HasColumnType("int");

                    b.Property<int>("ConnectedWeight")
                        .HasColumnType("int");

                    b.Property<int?>("OwnerPlanetId")
                        .HasColumnType("int");

                    b.HasKey("ConnectionId");

                    b.HasIndex("ConnectedToPlanetId");

                    b.HasIndex("OwnerPlanetId");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("DBContext.Models.Planet", b =>
                {
                    b.Property<int>("PlanetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanetId");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("DBContext.Models.Connection", b =>
                {
                    b.HasOne("DBContext.Models.Planet", "ConnectedTo")
                        .WithMany()
                        .HasForeignKey("ConnectedToPlanetId");

                    b.HasOne("DBContext.Models.Planet", "Owner")
                        .WithMany("Connections")
                        .HasForeignKey("OwnerPlanetId");
                });
#pragma warning restore 612, 618
        }
    }
}
